name: Build and Release Sonar Solidity Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean test package

      - name: Create ZIP of source code
        run: |
          zip -r sonar-solidity-updated.zip . -x "*.git*"

      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sonar-solidity-updated
          path: sonar-solidity-updated.zip

      - name: Create Release and Upload ZIP
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ github.run_number }}"
          name: "Release v${{ github.run_number }}"
          body: "Automated release of sonar-solidity-updated"
          files: sonar-solidity-updated.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
